### ISSUE TITLE
Always getting (undefined) next to the directory name

### ISSUE THREAD

**Issue by CrashyBang** [patrikholcak/hypertitle#1]
I am using [FISH shell](https://fishshell.com/) but even when I switch to `bash` or `node` like the demo I am still always getting `(undefined)`.

Like so:

![onpaste 20160825-182831](https://cloud.githubusercontent.com/assets/2978850/17959019/c1329280-6af1-11e6-94f7-b1b61e99172e.png)

Cheers.

**Comment by eamodio** [comment]
I am seeing the same thing with bash

**Comment by patrikholcak** [comment]
Sorry, I don’t have the time to maintain this project anymore. Check out https://github.com/sdomino/hyperterm-tab-cwd, might work.
